from __future__ import annotations

from langchain_text_splitters import Language

# Extension → Language
EXT_TO_LANGUAGE: dict[str, Language] = {
    # C
    ".c": Language.C,
    ".h": Language.C,
    # C++
    ".cpp": Language.CPP,
    ".cc": Language.CPP,
    ".cxx": Language.CPP,
    ".hpp": Language.CPP,
    # Python
    ".py": Language.PYTHON,
    # Java
    ".java": Language.JAVA,
    # JavaScript
    ".js": Language.JS,
    ".mjs": Language.JS,
    ".cjs": Language.JS,
    # TypeScript
    ".ts": Language.TS,
    ".tsx": Language.TS,
    # Go
    ".go": Language.GO,
    # Rust
    ".rs": Language.RUST,
    # Ruby
    ".rb": Language.RUBY,
    # Kotlin
    ".kt": Language.KOTLIN,
    ".kts": Language.KOTLIN,
    # Swift
    ".swift": Language.SWIFT,
}

PROSE_CATEGORIES = {"requirement"}

PROSE_EXTENSIONS = {
    ".txt",
    ".text",
    ".md",
    ".markdown",
    ".pdf",
    ".doc",
    ".docx",
    ".rtf",
}

FALLBACK_SEPARATORS = ["\n\n", "\n", " ", ""]

ASCII_OR_MARKDOWN_TABLE_RE = (
    r"(?ms)(^\s*\+[+\-=:\s]+\+\s*\n(?:^\s*\|.*\|\s*\n|^\s*\+[+\-=:\s]+\+\s*\n){2,})|"
    r"(^\s*\|.+\|\s*\n^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$)"
)

TABLE_PROSE_SEPARATORS = [
    "\n\n",
    "\n# ",
    "\n## ",
    "\n### ",
    "\n#### ",
    "\n- ",
    "\n* ",
    "\n• ",
    "\n1. ",
    "\n2. ",
    "\n3. ",
    "\n",
    ". ",
    "; ",
    ", ",
    " ",
    "",
]

PLAIN_PROSE_SEPARATORS = ["\n\n", "\n", ". ", " ", ""]

SOURCE_CODE_SEPARATORS_BY_LANGUAGE: dict[Language, list[str]] = {
    Language.C: [
        "\n\n",
        "\n#include ",
        "\n#define ",
        "\ntypedef ",
        "\nstruct ",
        "\nenum ",
        "\nstatic ",
        "\nextern ",
        "\nvoid ",
        "\nint ",
        "\nchar ",
        "\nlong ",
        "\nshort ",
        "\nfloat ",
        "\ndouble ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.CPP: [
        "\n\n",
        "\n#include ",
        "\nnamespace ",
        "\nclass ",
        "\nstruct ",
        "\nenum ",
        "\ntemplate ",
        "\npublic:",
        "\nprivate:",
        "\nprotected:",
        "\nstatic ",
        "\nvirtual ",
        "\nvoid ",
        "\nint ",
        "\nauto ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.PYTHON: [
        "\n\n",
        "\nclass ",
        "\ndef ",
        "\nasync def ",
        "\n@property",
        "\nif __name__",
        "\nimport ",
        "\nfrom ",
        "\nreturn ",
        "\n",
        " ",
        "",
    ],
    Language.JAVA: [
        "\n\n",
        "\npackage ",
        "\nimport ",
        "\npublic class ",
        "\nclass ",
        "\ninterface ",
        "\nenum ",
        "\npublic ",
        "\nprivate ",
        "\nprotected ",
        "\nstatic ",
        "\n@Override",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.JS: [
        "\n\n",
        "\nimport ",
        "\nexport ",
        "\nclass ",
        "\nfunction ",
        "\nasync function ",
        "\nconst ",
        "\nlet ",
        "\nvar ",
        "\nmodule.exports",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.TS: [
        "\n\n",
        "\nimport ",
        "\nexport ",
        "\ninterface ",
        "\ntype ",
        "\nenum ",
        "\nclass ",
        "\nfunction ",
        "\nasync function ",
        "\nconst ",
        "\nlet ",
        "\npublic ",
        "\nprivate ",
        "\nprotected ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.GO: [
        "\n\n",
        "\npackage ",
        "\nimport ",
        "\ntype ",
        "\nstruct ",
        "\ninterface ",
        "\nfunc ",
        "\nvar ",
        "\nconst ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.RUST: [
        "\n\n",
        "\nuse ",
        "\npub mod ",
        "\nmod ",
        "\npub struct ",
        "\nstruct ",
        "\npub enum ",
        "\nenum ",
        "\nimpl ",
        "\npub trait ",
        "\ntrait ",
        "\npub fn ",
        "\nfn ",
        "\nlet ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.RUBY: [
        "\n\n",
        "\nmodule ",
        "\nclass ",
        "\ndef ",
        "\nprivate",
        "\nprotected",
        "\npublic",
        "\nrequire ",
        "\ninclude ",
        "\nreturn ",
        "\n",
        " ",
        "",
    ],
    Language.KOTLIN: [
        "\n\n",
        "\npackage ",
        "\nimport ",
        "\nclass ",
        "\ninterface ",
        "\ndata class ",
        "\nsealed class ",
        "\nenum class ",
        "\nobject ",
        "\ncompanion object",
        "\nfun ",
        "\nprivate ",
        "\npublic ",
        "\ninternal ",
        "\nprotected ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.SWIFT: [
        "\n\n",
        "\nimport ",
        "\nprotocol ",
        "\nclass ",
        "\nstruct ",
        "\nenum ",
        "\nextension ",
        "\nactor ",
        "\nfunc ",
        "\ninit(",
        "\nvar ",
        "\nlet ",
        "\nprivate ",
        "\npublic ",
        "\ninternal ",
        "\nfileprivate ",
        "\nreturn ",
        "\n",
        ";",
        " ",
        "",
    ],
}

TEST_SEPARATORS_BY_LANGUAGE: dict[Language, list[str]] = {
    Language.C: [
        "\n\n",
        "\nstatic void ",
        "\nstatic int ",
        "\nCU_add_test(",
        "\n#ifdef ",
        "\n#ifndef ",
        "\n#if ",
        "\n#else",
        "\n#endif",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.CPP: [
        "\n\n",
        "\nTEST(",
        "\nTEST_F(",
        "\nTEST_P(",
        "\nTYPED_TEST(",
        "\nTEST_CASE(",
        "\nSCENARIO(",
        "\nSECTION(",
        "\nstatic void ",
        "\nclass ",
        "\nstruct ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.PYTHON: [
        "\n\n",
        "\nclass Test",
        "\ndef test_",
        "\nasync def test_",
        "\ndef setUp",
        "\ndef tearDown",
        "\n@pytest.",
        "\n",
        " ",
        "",
    ],
    Language.JAVA: [
        "\n\n",
        "\n@Test",
        "\n@ParameterizedTest",
        "\n@BeforeEach",
        "\n@AfterEach",
        "\n@Before",
        "\n@After",
        "\npublic void test",
        "\nvoid test",
        "\npublic class ",
        "\nclass ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.JS: [
        "\n\n",
        "\ndescribe(",
        "\ncontext(",
        "\nit(",
        "\ntest(",
        "\nbeforeEach(",
        "\nafterEach(",
        "\nbefore(",
        "\nafter(",
        "\nbeforeAll(",
        "\nafterAll(",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.TS: [
        "\n\n",
        "\ndescribe(",
        "\ncontext(",
        "\nit(",
        "\ntest(",
        "\nbeforeEach(",
        "\nafterEach(",
        "\nbeforeAll(",
        "\nafterAll(",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.GO: [
        "\n\n",
        "\nfunc Test",
        "\nfunc Benchmark",
        "\nfunc Example",
        "\nfunc Fuzz",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.RUST: [
        "\n\n",
        "\n#[test]",
        "\n#[tokio::test]",
        "\n#[cfg(test)]",
        "\nmod tests",
        "\nfn test_",
        "\nfn ",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.RUBY: [
        "\n\n",
        "\ndescribe ",
        "\ncontext ",
        "\nit ",
        "\ntest ",
        "\ndef test_",
        "\n",
        " ",
        "",
    ],
    Language.KOTLIN: [
        "\n\n",
        "\n@Test",
        "\n@BeforeEach",
        "\n@AfterEach",
        "\nfun test",
        "\nfun `",
        "\nclass ",
        "\nshould(",
        "\ncontext(",
        "\ndescribe(",
        "\n",
        ";",
        " ",
        "",
    ],
    Language.SWIFT: [
        "\n\n",
        "\nfunc test",
        "\nfinal class ",
        "\nclass ",
        "\n",
        ";",
        " ",
        "",
    ],
}

FALLBACK_TEST_SEPARATORS = [
    "\n\n",
    "\n@Test",
    "\ndescribe(",
    "\ncontext(",
    "\nit(",
    "\ntest(",
    "\ndef test_",
    "\nasync def test_",
    "\nfunc test",
    "\nfunc Test",
    "\nTEST(",
    "\nTEST_F(",
    "\nTEST_CASE(",
    "\nclass Test",
    "\n",
    ";",
    " ",
    "",
]

FALLBACK_SOURCE_CODE_SEPARATORS = [
    "\n\n",
    "\npackage ",
    "\nimport ",
    "\ninclude ",
    "\nclass ",
    "\ninterface ",
    "\nstruct ",
    "\nenum ",
    "\ntype ",
    "\nprotocol ",
    "\nextension ",
    "\ndef ",
    "\nfunction ",
    "\nfunc ",
    "\nfn ",
    "\npublic ",
    "\nprivate ",
    "\nprotected ",
    "\nstatic ",
    "\nasync ",
    "\nreturn ",
    "\n",
    ";",
    " ",
    "",
]

PROSE_RECORD_START_RE = r"^\s*(?:[A-Za-z]{1,10}\d+\b|\d+[.)](?=\s|$))"
